### ISSUE TITLE
Bug located in workflow ci_cd.yml file

### ISSUE THREAD

**Issue by dipinknair** [ansys/pymechanical-embedding-examples#49]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

## Gives false positive on workflow

Run xvfb-run /install/ansys_inc/v232/aisol/.workbench_lite make -C doc html
make: Entering directory '/__w/pymechanical-embedding-examples/pymechanical-embedding-examples/doc'
Running Sphinx v7.0.1

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sphinx/config.py", line 354, in eval_config_file
    exec(code, namespace)  # NoQA: S102
  File "/__w/pymechanical-embedding-examples/pymechanical-embedding-examples/doc/source/conf.py", line 1[17](https://github.com/ansys/pymechanical-embedding-examples/actions/runs/5953897532/job/16149248352?pr=48#step:9:18), in <module>
    pyvista.rcParams["window_size"] = np.array([1024, 768])
  File "/usr/local/lib/python3.8/dist-packages/pyvista/__init__.py", line 95, in __getattr__
    raise AttributeError(f"module 'pyvista' has no attribute '{name}'") from None
AttributeError: module 'pyvista' has no attribute 'rcParams'

make: [Makefile:[22](https://github.com/ansys/pymechanical-embedding-examples/actions/runs/5953897532/job/16149248352?pr=48#step:9:23): html] Error 2 (ignored)
make: Leaving directory '/__w/pymechanical-embedding-examples/pymechanical-embedding-examples/doc'

@RobPasMue 

### 📝 Steps to reproduce

locally run `.\doc\make.bat html`

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

v232  &  v241

### 🐍 Which Python version are you using?

3.11

### 📦 Installed packages

```shell
accessible-pygments==0.0.4
alabaster==0.7.13
ansys-api-mechanical==0.1.0
ansys-api-platform-instancemanagement==1.0.0
ansys-mechanical-core==0.10.1
ansys-platform-instancemanagement==1.1.2
ansys-pythonnet==3.1.0rc1
ansys-sphinx-theme==0.10.3
ansys-tools-path==0.3.1
anyio==3.7.1
appdirs==1.4.4
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
async-lru==2.0.4
attrs==23.1.0
Babel==2.12.1
backcall==0.2.0
beautifulsoup4==4.12.2
bleach==6.0.0
bokeh==3.1.1
cachetools==5.3.1
certifi==2023.7.22
cffi==1.15.1
chardet==5.2.0
charset-normalizer==3.2.0
click==8.1.7
clr-loader==0.2.6
colorama==0.4.6
comm==0.1.4
contourpy==1.1.0
cycler==0.11.0
debugpy==1.6.7.post1
decorator==5.1.1
defusedxml==0.7.1
distlib==0.3.7
docutils==0.20.1
executing==1.2.0
fastjsonschema==2.18.0
filelock==3.12.2
flit==3.9.0
flit_core==3.9.0
fonttools==4.42.1
fqdn==1.5.1
grpcio==1.57.0
idna==3.4
imagesize==1.4.1
importlib-metadata==6.8.0
ipydatawidgets==4.3.5
ipykernel==6.25.1
ipython==8.14.0
ipywidgets==8.1.0
isoduration==20.11.0
jaraco.classes==3.3.0
jedi==0.19.0
Jinja2==3.1.2
json5==0.9.14
jsonpointer==2.4
jsonschema==4.19.0
jsonschema-specifications==2023.7.1
jupyter-events==0.7.0
jupyter-lsp==2.2.0
jupyter-sphinx==0.4.0
jupyter_client==8.3.0
jupyter_core==5.3.1
jupyter_server==2.7.2
jupyter_server_terminals==0.4.4
jupyterlab==4.0.5
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.8
jupyterlab_server==2.24.0
keyring==24.2.0
kiwisolver==1.4.4
linkify-it-py==2.0.2
livereload==2.6.3
Markdown==3.4.4
markdown-it-py==2.2.0
MarkupSafe==2.1.3
matplotlib==3.7.2
matplotlib-inline==0.1.6
mdit-py-plugins==0.4.0
mdurl==0.1.2
mistune==3.0.1
more-itertools==10.1.0
nbclient==0.8.0
nbconvert==7.7.4
nbformat==5.9.2
nest-asyncio==1.5.7
notebook_shim==0.2.3
numpy==1.24.3
numpydoc==1.5.0
overrides==7.4.0
packaging==23.1
pandas==2.0.3
pandocfilters==1.5.0
panel==1.1.0
param==1.13.0
parso==0.8.3
pickleshare==0.7.5
Pillow==10.0.0
pkginfo==1.9.6
platformdirs==3.10.0
plotly==5.16.1
pluggy==1.2.0
pooch==1.7.0
prometheus-client==0.17.1
prompt-toolkit==3.0.39
protobuf==3.20.3
psutil==5.9.5
pure-eval==0.2.2
pycparser==2.21
pydata-sphinx-theme==0.13.3
Pygments==2.16.1
pypandoc==1.11
pyparsing==3.0.9
pyproject-api==1.5.4
python-dateutil==2.8.2
python-json-logger==2.0.7
pythreejs==2.4.2
pytz==2023.3
pyvista==0.41.1
pyviz_comms==3.0.0
pywin32==306
pywin32-ctypes==0.2.2
pywinpty==2.0.11
PyYAML==6.0.1
pyzmq==25.1.1
readme-renderer==41.0
referencing==0.30.2
requests==2.31.0
requests-toolbelt==1.0.0
rfc3339-validator==0.1.4
rfc3986==2.0.0
rfc3986-validator==0.1.1
rich==13.5.2
rpds-py==0.9.2
scooby==0.7.2
Send2Trash==1.8.2
six==1.16.0
sniffio==1.3.0
snowballstemmer==2.2.0
soupsieve==2.4.1
Sphinx==7.0.1
sphinx-autobuild==2021.3.14
sphinx-autodoc-typehints==1.24.0
sphinx-copybutton==0.5.1
sphinx-gallery==0.14.0
sphinx-notfound-page==0.8.3
sphinxcontrib-applehelp==1.0.7
sphinxcontrib-devhelp==1.0.5
sphinxcontrib-htmlhelp==2.0.4
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.6
sphinxcontrib-serializinghtml==1.1.9
sphinxemoji==0.2.0
stack-data==0.6.2
tenacity==8.2.3
terminado==0.17.1
tinycss2==1.2.1
tomli_w==1.0.0
tornado==6.3.3
tox==4.10.0
tqdm==4.66.1
traitlets==5.9.0
traittypes==0.2.1
twine==4.0.2
typing_extensions==4.7.1
tzdata==2023.3
uc-micro-py==1.0.2
uri-template==1.3.0
urllib3==2.0.4
virtualenv==20.24.3
vtk==9.2.6
wcwidth==0.2.6
webcolors==1.13
webencodings==0.5.1
websocket-client==1.6.2
widgetsnbextension==4.0.8
xyzservices==2023.7.0
zipp==3.16.2
```

**Comment by RobPasMue** [comment]
Let's look later into it

**Comment by RobPasMue** [comment]
Also, the issue related to PyVista is addressed here

https://github.com/ansys/pymapdl/blob/23743afc54e85fab2cec581fd9331e73aaa1cd1d/doc/source/conf.py#L22C53-L27

**Comment by RobPasMue** [comment]
Please make two different PRs for each suggestion
